version: '3.8'

services:
  crowdin:
    image: crowdin/cli:3.7.9
    volumes:
        - ".:/app"
    env_file:
      - env.d/development/crowdin
    user: ${DOCKER_USER:-1000}
    working_dir: /app
  node:
    image: node:16.15
    working_dir: /app
    user: ${DOCKER_USER:-1000}
    volumes:
      - .:/app
